### ISSUE TITLE
jest -t 'some spec' still launches browser contexts for suites where no tests are run

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#112] opened 2020-04-25 12:18 UTC
The following command `jest -t 'some spec'` still launches browser contexts for suites where no tests are run. This is unnecessary and bit unfortunate in the case where you run in headful mode.

Imagine you have one very specific test case like `it('uploads file in the cool-app')` and you run `jest -t 'uploads file in the cool-app'`, but you have multiple test files. Then each test file will launch a browser context and then quickly close it, even though Jest will only execute one test case.

**Comment by mmarkelov** [comment] 2020-07-02 10:01
I got some research on it and I don't have any ideas about it. We can't use **runner** to skip initial process. Also I tried to use **environment** for this. I also tried **handleTestEvent**, but the problem is that `test skip event` will run after `beforeAll` and `beforeEach` events

**Comment by creage** [comment] 2020-07-10 14:28
We see this issue too. And it is annoying.

@mmarkelov I know it might sound a bit against API, but can we postpone `setup` code until we actually receive `test_start` event in the `handleTestEvent()` handler? And teardown our stuff only if it was actually setup? This way we can avoid create/destroy cycles on skipped test.

**Comment by thernstig** [comment] 2020-07-12 08:38
Isn't there a way to get the test cases that will be run, inside the custom test environment? And you can check the length of it? It's possible that info is not available at that time?

**Comment by mmarkelov** [comment] 2021-05-18 11:54
I just released **next** version, hope that i found out the way to skip it

**Comment by mmarkelov** [comment] 2021-05-30 14:12
should be fixed in **1.6.0**

**Closed by mmarkelov** 2021-05-30 14:12 UTC
