### ISSUE TITLE
WebKit fails on basic test

### ISSUE THREAD

**Issue by jsjoeio** [playwright-community/jest-playwright#659] opened 2021-03-30 18:27 UTC
**Describe the bug**
Basic test (from example) fails on WebKit

**To Reproduce**
1. `git clone https://github.com/jsjoeio/jest-playwright-repro.git`
2. `yarn`
3. `yarn test` or `yarn test:debug`

**Expected behavior**
Test runs using browser `webkit` and passes.

**Screenshots**

https://user-images.githubusercontent.com/3806031/113037520-51bed380-914a-11eb-9846-8a0f3ea712af.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.2.2 (20D80)
 - Playwright version: 1.10.0
 - jest-playwright version: 1.5.1

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
  preset: "jest-playwright-preset",
  transform: {
    "^.+\\.ts$": "ts-jest",
  },
  testEnvironmentOptions: {
    "jest-playwright": {
      browsers: ["webkit"],
    },
  },
}
```

**Additional context**
What I've tried:
-  setting `exitOnPageError: false` per [comment](https://github.com/playwright-community/jest-playwright/issues/614#issuecomment-791548634)
- running same test with `chromium` and `firefox` (it works as expected)

🤞 Hoping I've done something wrong in my setup and it's a simple fix (not an actual bug).

**Comment by mxschmitt** [comment] 2021-03-30 21:00
Could you try to run this with Node.js directly to exclude that it has to do with this project?

```js
// @ts-check
const playwright = require('playwright');

(async () => {
    const browser = await playwright.webkit.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('https://www.whatismybrowser.com/');
    await page.screenshot({ path: `example.png` });
    await browser.close();
})();
```

**Comment by jsjoeio** [comment] 2021-03-30 21:03
Okay I ran that with Node and it had no issues. Here's the screenshot: 
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3806031/113056436-a705df80-9160-11eb-8381-f81c5c174eab.png">

**Comment by mxschmitt** [comment] 2021-03-30 21:10
@jsjoeio thank you so much for your reproducible, I will transfer it over to the Playwright repo, since it seems like a reproducible WebKit crash on Mac OS.

**Comment by mxschmitt** [comment] 2021-03-30 21:35
Closing since it's an upstream problem. Was able to make a small reproducible, thanks for filing!

**Closed by mxschmitt** 2021-03-30 21:35 UTC
Labels: triaging
