### ISSUE TITLE
[Question]: can jest-playwright use the import-expotr module

### ISSUE THREAD

**Issue by ViaMay** [playwright-community/jest-playwright#767] opened 2021-07-08 06:07 UTC
question
I used this project https://github.com/playwright-community/jest-playwright for start my tests. But I have a problem.

I want to use Import and Export (https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_modules_ecmascript_modules) for my code.
I can’t understand it is possible to configure its or you don’t support it yet?

**Comment by ryneeverett** [comment] 2021-07-10 19:43
Duplicate of #718.

**Closed** 2021-07-10 20:14 UTC
